/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "RCC.h"
#include "GPIO.h"


int main(void)
{


	RCC_GPIOA_CLK_ENB();

	GPIO_InitTypeDef_t config;
	config.Mode = OUTPUT;
	config.Otype = OPUSHPULL;
	config.Speed = HSPEED;
	config.PuPD = 0;

	GPIO_Init(GPIOA, GPIO_PIN_5, &config);
	while(1)
	{
		int i = 1000000;
		GPIO_Pin_Write(GPIOA, GPIO_PIN_5, GPIO_PIN_ENABLE);
		while(i>0)
		{
			i--;
		}
		GPIO_Pin_Write(GPIOA, GPIO_PIN_5, GPIO_PIN_DISABLE);
		 i = 1000000;
		while(i>0)
		{
			i--;
		}
	}

	for(;;);
}
